//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolForm {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class frmLogin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmLogin() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchoolForm.frmLogin", typeof(frmLogin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 Flat 的 System.Windows.Forms.FlatStyle 类型的本地化资源。
        /// </summary>
        internal static System.Windows.Forms.FlatStyle btnCalce_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("btnCalce.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 [Font: Name=宋体, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False] 的 System.Drawing.Font 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Font btnCalce_Font {
            get {
                object obj = ResourceManager.GetObject("btnCalce.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {X=299,Y=291} 的 System.Drawing.Point 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Point btnCalce_Location {
            get {
                object obj = ResourceManager.GetObject("btnCalce.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {Width=84, Height=22} 的 System.Drawing.Size 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Size btnCalce_Size {
            get {
                object obj = ResourceManager.GetObject("btnCalce.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 6 的 System.Int32 类型的本地化资源。
        /// </summary>
        internal static int btnCalce_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnCalce.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string btnCalce_Text {
            get {
                return ResourceManager.GetString("btnCalce.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 Flat 的 System.Windows.Forms.FlatStyle 类型的本地化资源。
        /// </summary>
        internal static System.Windows.Forms.FlatStyle btnLogin_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("btnLogin.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 [Font: Name=宋体, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False] 的 System.Drawing.Font 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Font btnLogin_Font {
            get {
                object obj = ResourceManager.GetObject("btnLogin.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {X=170,Y=292} 的 System.Drawing.Point 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Point btnLogin_Location {
            get {
                object obj = ResourceManager.GetObject("btnLogin.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {Width=84, Height=22} 的 System.Drawing.Size 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Size btnLogin_Size {
            get {
                object obj = ResourceManager.GetObject("btnLogin.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 5 的 System.Int32 类型的本地化资源。
        /// </summary>
        internal static int btnLogin_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnLogin.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string btnLogin_Text {
            get {
                return ResourceManager.GetString("btnLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 NoControl 的 System.Windows.Forms.ImeMode 类型的本地化资源。
        /// </summary>
        internal static System.Windows.Forms.ImeMode cboType_ImeMode {
            get {
                object obj = ResourceManager.GetObject("cboType.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        internal static string cboType_Items {
            get {
                return ResourceManager.GetString("cboType.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 学生 的本地化字符串。
        /// </summary>
        internal static string cboType_Items1 {
            get {
                return ResourceManager.GetString("cboType.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 {X=278,Y=256} 的 System.Drawing.Point 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Point cboType_Location {
            get {
                object obj = ResourceManager.GetObject("cboType.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {Width=147, Height=23} 的 System.Drawing.Size 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Size cboType_Size {
            get {
                object obj = ResourceManager.GetObject("cboType.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 0 的 System.Int32 类型的本地化资源。
        /// </summary>
        internal static int cboType_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cboType.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        internal static bool lblName_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblName.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 [Font: Name=宋体, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False] 的 System.Drawing.Font 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Font lblName_Font {
            get {
                object obj = ResourceManager.GetObject("lblName.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {X=171,Y=183} 的 System.Drawing.Point 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Point lblName_Location {
            get {
                object obj = ResourceManager.GetObject("lblName.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {Width=110, Height=29} 的 System.Drawing.Size 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Size lblName_Size {
            get {
                object obj = ResourceManager.GetObject("lblName.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 0 的 System.Int32 类型的本地化资源。
        /// </summary>
        internal static int lblName_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblName.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 用 户 名： 的本地化字符串。
        /// </summary>
        internal static string lblName_Text {
            get {
                return ResourceManager.GetString("lblName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        internal static bool lblPwd_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblPwd.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 [Font: Name=宋体, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False] 的 System.Drawing.Font 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Font lblPwd_Font {
            get {
                object obj = ResourceManager.GetObject("lblPwd.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {X=171,Y=218} 的 System.Drawing.Point 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Point lblPwd_Location {
            get {
                object obj = ResourceManager.GetObject("lblPwd.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {Width=110, Height=29} 的 System.Drawing.Size 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Size lblPwd_Size {
            get {
                object obj = ResourceManager.GetObject("lblPwd.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 0 的 System.Int32 类型的本地化资源。
        /// </summary>
        internal static int lblPwd_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblPwd.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 密    码： 的本地化字符串。
        /// </summary>
        internal static string lblPwd_Text {
            get {
                return ResourceManager.GetString("lblPwd.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 True 的 System.Boolean 类型的本地化资源。
        /// </summary>
        internal static bool lblType1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("lblType1.AutoSize", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 [Font: Name=宋体, Size=12, Units=3, GdiCharSet=1, GdiVerticalFont=False] 的 System.Drawing.Font 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Font lblType1_Font {
            get {
                object obj = ResourceManager.GetObject("lblType1.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {X=171,Y=253} 的 System.Drawing.Point 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Point lblType1_Location {
            get {
                object obj = ResourceManager.GetObject("lblType1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {Width=110, Height=29} 的 System.Drawing.Size 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Size lblType1_Size {
            get {
                object obj = ResourceManager.GetObject("lblType1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 0 的 System.Int32 类型的本地化资源。
        /// </summary>
        internal static int lblType1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lblType1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 登录类型： 的本地化字符串。
        /// </summary>
        internal static string lblType1_Text {
            get {
                return ResourceManager.GetString("lblType1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 {X=278,Y=184} 的 System.Drawing.Point 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Point txtName_Location {
            get {
                object obj = ResourceManager.GetObject("txtName.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {Width=147, Height=25} 的 System.Drawing.Size 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Size txtName_Size {
            get {
                object obj = ResourceManager.GetObject("txtName.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 1 的 System.Int32 类型的本地化资源。
        /// </summary>
        internal static int txtName_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtName.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {X=278,Y=221} 的 System.Drawing.Point 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Point txtPwd_Location {
            get {
                object obj = ResourceManager.GetObject("txtPwd.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 * 的 System.Char 类型的本地化资源。
        /// </summary>
        internal static char txtPwd_PasswordChar {
            get {
                object obj = ResourceManager.GetObject("txtPwd.PasswordChar", resourceCulture);
                return ((char)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 {Width=147, Height=25} 的 System.Drawing.Size 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Size txtPwd_Size {
            get {
                object obj = ResourceManager.GetObject("txtPwd.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 1 的 System.Int32 类型的本地化资源。
        /// </summary>
        internal static int txtPwd_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtPwd.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
